### ISSUE TITLE
Nicoulaj prompt doesn't show directory at all

### ISSUE THREAD

**Issue by endrjux** [sorin-ionescu/prezto#1051]
Nicoulaj prompt doesn't show directory at all. No matter if it's inside a repo or not. Inside a repo, branch is correctly shown on the left, but on the right there is only `❯` and nothing more. Return value coloring works fine. Zsh 5.2, Prezto from git, Arch Linux.
![image](https://cloud.githubusercontent.com/assets/688476/11913655/1f597988-a66b-11e5-9948-1d9d7745fbcc.png)
(I customized `user_char` and `root_char` because of #911, this doesn't affect the issue described)
This is how it should look (screenshot from prompt source):
![](http://i.imgur.com/Xe1bu.png)

**Comment by sleep** [comment]
+1
Same for me

Zsh 5.2
Prezto from git
NixOS

Interestingly, it runs fine on my osx partition...
Also, it ran fine on my Linux setup a year ago.

**Comment by sleep** [comment]
On osx, nicoulaj seems to run fine.
 `zsh --version` gets me
```
zsh 5.0.8 (x86_64-apple-darwin14.4.0)
```

**Comment by endrjux** [comment]
So it seems zsh releases after 5.0.8 changed something that breaks this prompt. Or maybe this is a bug in zsh. I don't really see anything related in http://zsh.sourceforge.net/releases.html But I found this: http://www.zsh.org/mla/workers/2015/msg03258.html and I think it may be related (see [line 53](https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/functions/prompt_nicoulaj_setup#L53) of prompt).

**Comment by sorin-ionescu** [comment]
I confirm this bug, but I don't know how `%${max_path_chars}<...<` at line 56 works. I'll have to read the man page. I can replace it with the path function from my theme as a workaround.

I haven't looked in years if @nicoulaj has updated this theme in his dotfiles.

**Comment by nicoulaj** [comment]
It still works for me (zsh 5.2).

This is the code I use, unchaged for years: https://github.com/nicoulaj/dotfiles/blob/master/.config/zsh/functions/prompts/prompt_nicoulaj_setup

**Comment by sorin-ionescu** [comment]
It looks slightly different. I'll sync it.

**Comment by endrjux** [comment]
Well, I tried to modify prompt source to match the original. I couldn't identify any place that may be responsible for the issue. I just changed `Functions/VCS_Info/VCS_INFO_nvcsformats` in zsh (see link in my comment above) and theme works ok without any changes.

Even if this can be fixed by modifying something in the theme (because it works for @nicoulaj) this is clearly a zsh bug. It's been already fixed upstream (no new release yet).

**Comment by ohcibi** [comment]
@nicoulaj 's new prompt is not working at all for me. Prompt contains plain color codes when I'm using it. See screenshot:
![screenshot 2016-05-19 11 47 03](https://cloud.githubusercontent.com/assets/61993/15389486/76c3f284-1db7-11e6-8aef-72cc790d5e65.png)

Does this prompt depend on anything else? Like any special module?

I have the same problem with my own prompt where I borrowed this concept from @nicoulaj 's prompt. I played a bit around with both prompts and found out that `$vcs_info_msg_0_` is empty when zsh is started inside zsh and I am outside of a repository; I don't have this problem when I just start zsh. It only shows when I start `tmux` (where I noticed it) or with plain `zsh` inside running session (which I found out while debugging this).

@sorin-ionescu `%N<subst<foobarbaz` truncates the beginning of the string `foobarbaz` if it is longer than `N` chars and prepends it with the string `subst`. `%N>subst>` would truncate the end of the string and append `subst`.

So you can actually leave this bit out and just concentrate on `${vcs_info_msg_0_%%.}` which immediately follows and is empty - as I said - when zsh is running as a subprocess of zsh. (The trailing `%%.` is necessary but I don't know what for.)

Seems to be an issue with zsh's `vcs_info` but I'm not sure if this is due to wrong usage of it or a bug in `vcs_info`.

**Comment by ohcibi** [comment]
I want to add that `$vcs_info_msg_0_` is not showing the path of the git repository either. Thats done by `$vcs_info_msg_1_`, which simply works no matter if zsh is a subprocess or not.

**Comment by nicoulaj** [comment]
@ohcibi @endrjux @sleexyz This is a zsh bug: http://www.zsh.org/mla/workers/2015/msg03259.html
It was fixed one year ago (https://github.com/zsh-users/zsh/commit/4105f79a3a9b5a85c4ce167865e5ac661be160dc), but there was no release of zsh since then...
I confirm the prompt works fine in current zsh HEAD.

**Comment by ohcibi** [comment]
@Nicoulaj yes. I had the same problem in my prompt as well. Building zsh master works

**Comment by belak** [comment]
Is this still a bug? I'm also not 100% sure what the expected behavior is... whenever I'm inside a git directory with this prompt (zsh 5.4.2) the path seems to go away.

**Comment by endrjux** [comment]
@belak It should behave like this inside Git repo.

Source of original bug was fixed in zsh, this can be closed.

**Comment by belak** [comment]
Thanks for following up! Glad it's been fixed.
