### ISSUE TITLE
Ability to disable fortune through zpreztorc settings

### ISSUE THREAD

**Issue by rothgar** [sorin-ionescu/prezto#1076]
Ideally I think it's expected that user customizations are kept in zpreztorc and users shouldn't edit files in runcoms (correct me if I'm wrong).

However there's currently no way to disable fortunes without either uninstalling the package or commenting out these lines in zlogin
https://github.com/sorin-ionescu/prezto/blob/master/runcoms/zlogin#L19-L21

It'd be nice if this functionality was an optional module or environment variable.

**Comment by sorin-ionescu** [comment]
`.zpreztorc` is for `zstyles` buried deep in modules. The runcoms are expected to be edited.

**Comment by azah** [comment]
fortune should be disabled by default.

Please allow me to determine whether or not I want `fortune` to run on terminal startup; zsh, oh-my-zsh, zpresto, or anyone else should not decide that for me.

**Comment by ezintz** [comment]
I think you are not forced to use prezto and it was designed to be used by one person - I think at least at the beginning. You can simply uninstall the package and the problem is solved.

It sound like you are saying I want to buy that meal in restaurant but want to cook it yourself. But I can agree that there can be an option to disable it.
