### ISSUE TITLE
prezto update and brew command completion no longer working

### ISSUE THREAD

**Issue by wonbyte** [sorin-ionescu/prezto#1101]
I did a prezto update and now when I type `brew up <tab> ` I get:
-- no matches found --

It should display the update or upgrade command. 

Any ideas what I need to do to get this working again? Nothing was changed except doing a zprezto update.

**Comment by wonbyte** [comment]
Tried `rm -f ~/.zcompdump; compinit` but no luck... Any ideas?

**Comment by malde** [comment]
I've stumbled upon the same problem, but I don't think it's caused by prezto.
There is an issue in the homebrew repo [issue 49066](https://github.com/Homebrew/homebrew/issues/49066)
As far as I understand zsh-completions removed their own completions for brew, since homebrew does provide it's own set. 
I did however not manage to fix this.

**Comment by superlukas** [comment]
It's super easy; just create a symbolic link. See https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Tips-N'-Tricks.md#command-tab-completion

**Comment by wonbyte** [comment]
`~ ❯ brew up                                                           17:08:23 
 -- brew subcommand --
update         -- fetch latest version of Homebrew and all formulae
upgrade        -- upgrade outdated formulae
up             update         update-report  upgrade 
`

**Comment by superlukas** [comment]
@wonbyte That's likely an error in the brew completion file. I can't debug it because there's a lot of ruby in there, but I assume they iron out the kinks over time.

What I've noticed so far is that the completion is slower than it used to be (probably because of the ruby bits in there) and it completes "i" to "instal" instead of "install" (which is fine; it's an alias. But still...)

**Comment by wadkar** [comment]
@malde is correct. I faced similar issue, and workaround/fix is to:
```sh
ln -s "$(brew --prefix)/Library/Contributions/brew_zsh_completion.zsh" /usr/local/share/zsh/site-functions/_brew
```
see my [last comment](https://github.com/Homebrew/homebrew/issues/49066#issuecomment-196430383) on Homebrew/homebrew#49066
FWIW, that issue caused me to cleanup my `.zshrc` and I ended up using Prezto :-)

**Comment by wonbyte** [comment]
@wadkar so just doing the symlink is sufficient correct? No need to add

fpath=($(brew --prefix)/share/zsh-completions $fpath)
autoload -Uz compinit
compinit

**Comment by superlukas** [comment]
@wonbyte 

The symlink installs the homebrew completion file to a place where zsh can find it (i.e., to a path in your $fpath). The code you pasted adds the directory homebrew installed the zsh-completion package in to your $fpath (again, so that zsh can find it).

It seems to me that a lot of people get confused where the boundaries between zsh, homebrew, and zsh-completions are. None of these have anything to do whatsoever. I, for example, have added the zsh-completions repo as a submodule to my dotfiles rather than installing it via homebrew.

**Comment by wonbyte** [comment]
@superlukas

Ok so I never installed the zsh-completions. I just brew installed zsh then added presto so I think I'm g2g with just the symlink.

**Comment by sorin-ionescu** [comment]
Prezto comes with zsh-completions. Don't install it separately.

**Comment by superlukas** [comment]
I completely forgot about that. Prezto users don't have to worry about any of the fpath stuff I mentioned. Sorin took care of that for you.

**Comment by wonbyte** [comment]
@superlukas ok cool. So just have to source the brew completions since zsh-completions removed it

**Comment by wadkar** [comment]
yep, thats what the symlinking does
