### ISSUE TITLE
Square Characters in cli  prompt

### ISSUE THREAD

**Issue by smmarrocco** [sorin-ionescu/prezto#1195]
Hello,

I know this has something to do with my locale - but  I can assure it is set to en_US.UTF-8.

For some reason zpresto is only giving me "squares" as characters.

Can anyone help me with this issue?

**Comment by ratheesh** [comment]
If you are using prompt which has powerline symbols, make sure to use font patched with powerline symbols in your terminal emulator.

**Comment by belak** [comment]
It depends on which theme and font you're using. There's a bit of info about fonts in the powerline fonts repo: https://github.com/powerline/fonts

Quite a few of the themes in here use some of the powerline characters, so that might be what you're seeing.

I'm going to close this for now because it appears to have been a user configuration issue and there hasn't been a response in almost 6 months.
