### ISSUE TITLE
modules/utility htop is aliased to top

### ISSUE THREAD

**Issue by samcv** [sorin-ionescu/prezto#1337]
### Description

The names of existing programs should not be aliased to *other* programs. For something that aims to be an easy to install and configure zsh configuration, it should not go about aliasing one program to another. If I want to run top I run top. When I want to run htop I run htop. If the user wants to add an alias and *overwrite* an existing program that is fine, but the default setup should not do this.

### Expected behavior

Expected top to run.

### Actual behavior

htop ran

### Versions

  - Prezto commit: a75c637
  - ZSH version: 5.3.1
  - OS information: Linux x64

**Comment by belak** [comment]
Yeah, fair point. There are quite a few places where this was done in the past (as an example, there was a diff function which could use some git magic to get a colored diff - it was removed because it broke quite a few command line switches).

I think the idea behind this is that htop is preferred in quite a few instances for the average user, so if it's installed, it (mostly) made sense to alias top to it. I have to admit I've had quite a few servers where I've done something like this:

```
% htop
zsh: command htop not found
% sudo apt-get install htop
...
% htop
```

Having a single alias makes that easier but I still think this should be removed.

In the future I'd like to only alias things which have almost exactly the same functionality (like diff=colordiff) and respond to the same switches.

Anyway, I think this is valid, so I'd accept a pull request to do it (if I don't get around to it soon)... especially because in most cases it's just one more letter.

**Comment by samcv** [comment]
Awesome. Thanks @diraol
