### ISSUE TITLE
Disable Tmux module on TTY

### ISSUE THREAD

**Issue by benmezger** [sorin-ionescu/prezto#1353]
### Description

Not a bug nor a feature (probably), but is there anyway I can disable `modules/tmux` when using the `TTY` instead of a terminal emulator? Ocasually I use both, and on TTY `tmux` seems to mess up a few things (specially unicode). 

### Expected behavior

Detect if I am using a `TTY` and disable `modules/tmux` automatically.

### Actual behavior

When logging in on a `TTY`, it opens `tmux` by default and I am not able to get out of it. So disabling on `TTY` seems like the best option.

### Steps to Reproduce

Enable the following to your `zpreztorc`:

```
zplug 'modules/tmux', from:prezto
zstyle ':prezto:module:tmux:auto-start' local 'yes'
zstyle ':prezto:module:tmux:auto-start' remote 'yes'
```

### Versions

  - Prezto commit: 1c041c04339eeb45556acef5e1ac43742b20bda1
  - ZSH version: zsh 5.3.1 (x86_64-unknown-linux-gnu)
  - OS information: Linux anarchy 4.11.6-3-zen #1 ZEN SMP PREEMPT Thu Jun 22 13:47:45 UTC 2017 x86_64 GNU/Linux

**Comment by belak** [comment]
The easiest way I know of would be to use the value from $TERM to only enable auto-start if it matches your terminal emulator. Something like the following:

```
if [[ "$TERM" = xterm* ]]; then
  zstyle ':prezto:module:tmux:auto-start' local 'yes'
  zstyle ':prezto:module:tmux:auto-start' remote 'yes'
fi
```

This is not foolproof and it may not match all terminals (You'd have to add additional matching for anything that doesn't use something similar to xterm) but I think it would be safer to only set it when you know you're in a terminal, rather than disabling it when you're in a tty (TERM=linux usually).

**Comment by belak** [comment]
One additional thing worth noting... if you're using zplug, and they cache values, you may need a workaround but that would need to happen there.

I'm closing this for now because this should be something handled by the user if they want it. Doing it in the framework itself would be very error prone.
