### ISSUE TITLE
clearing the screen with CTRL-l eats the first line

### ISSUE THREAD

**Issue by deadc0de6** [sorin-ionescu/prezto#1487]
### Description

When clearing the screen with `CTRL+l` the first line of some two-lines prompts gets eaten. When using `clear` it doesn't.

Affected prompts: `superlinh` and `pure`

Unaffected prompts: `giddie` and `fade` among others

### Steps to Reproduce

1. change prompt to `superlinh` or `pure`
2. type `CTRL-l`
3. first line of the prompt gets eaten

This doesn't happen with other prompts like `giddie` or `fade`.

### Versions

  - Prezto commit:25d8db301d5939040ff4aa6e7211d27e74f2d0d9
  - ZSH version: 5.3.1 (debian) and 5.4.2 (arch)
  - OS information: debian stretch and arch linux
  - terminals tested: urxvt, termite, xterm, terminator

**Comment by belak** [comment]
This is most likely a duplicate of #1426

**Comment by deadc0de6** [comment]
interesting but `pure` works as expected with `echo -n`:
```
~
❯ echo -n hello world
hello world
~
❯ 
```

as does `superlinh`

**Comment by belak** [comment]
Oh, I see what you're saying now. My mistake.

**Comment by belak** [comment]
Just for clarification, where is the prompt superlinh from? That doesn't seem to be included in this repo or the old inactive community fork.

**Comment by belak** [comment]
Ok, after investigation, it looks like this is because of an interaction between how pure handles that first line (it's not a part of the PROMPT variable - it's printed manually as a part of precmd) and a hook it adds to clear the screen (which doesn't get set up if you load a module (like syntax-highlighting) before this prompt is loaded.

I don't completely understand how this interacts with the `clear` command  or what the best way would be to fix it... but I'm pretty sure this is what's going on.

**Comment by deadc0de6** [comment]
my bad I thought superlinh was in the repo, I found it here: https://github.com/linhmtran168/mac_dotfiles/blob/master/prompt_superlinh_setup

ok cool, thanks for the explanation. I had a parallel issue opened on `pure` for this (https://github.com/sindresorhus/pure/issues/355), will relay that there.

thanks again

**Comment by belak** [comment]
It looks like that prompt does something similar - it uses precmd to print out the first line of the prompt.

Thinking about it, storing the precmd portion of the prompt in a variable, including it in PROMPT, and using zle reset-prompt rather than printing it in precmd might be a way to fix it. We do something similar with the git info in the sorin prompt (https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/functions/prompt_sorin_setup#L35)

**Comment by mafredri** [comment]
I didn't realize we haven't cut a new release of Pure for so long. The master branch actually does keep the entire prompt in PS1 and uses zle reset-prompt. Would you mind testing out the master branch @deadc0de6?

**Comment by deadc0de6** [comment]
Sure.

It still happens with the master branch on debian stretch and zsh 5.3.1 at least.

**Comment by deadc0de6** [comment]
Ok I did it properly and yes, the master version works and does not eat the first line.

However I'm getting duplicate prompts and an error when using it:
```
❯ echo 'test'
test

~
❯ 
prompt_pure_async_callback:10: bad set of key/value pairs for associative array

~
❯ 
```

**Comment by deadc0de6** [comment]
thanks for your help !

**Comment by belak** [comment]
I've updated pure to the latest tag, so this should be fixed for that prompt. Thanks for bringing it up!
