### ISSUE TITLE
ssh pass doesn't get saved, continues to prompt

### ISSUE THREAD

**Issue by leshow** [sorin-ionescu/prezto#1489]
### Description

Recently pulled from master and updated, ssh-add no longer appears to run on my ssh ids
### Expected behavior

my defined ssh-ids should be added
### Actual behavior

I get prompted for every ssh action
### Steps to Reproduce
If I revert ssh/init.zsh to this:
```
  if (( ${#_ssh_identities} > 0 )); then
	ssh-add "$_ssh_dir/${^_ssh_identities[@]}"  < /dev/null 2> /dev/null
  else
	ssh-add  < /dev/null 2> /dev/null
  fi
```

everything works as expected, or at least as it did before (I login to tty, I put my username/pass, and then am prompted for my ssh password)

I noticed this change: https://github.com/flying-sheep/prezto/commit/5a72d7c31f72c99c984964e65ec6d2471098d996

Am I supposed to define `SSH_ASKPASS` somewhere? I can't use x11-ssh-askpass because I don't have x11 loaded at this point in time (as I saw in the change before this one). I log in, and I run `startx` if I want to initiate an xsession. I'd like for my ssh-agent to behave regardless of environment.

### Versions

  - Prezto commit: master branch
  - ZSH version: 5.4.2
  - OS information: Linux 4.13.7-1-ARCH

**Comment by belak** [comment]
After reviewing a number of the other PRs relating to this, I've thrown together this one to try and fix this... again.

If you could try that branch and let me know if it fixes the problem for you, that would be much appreciated.

**Comment by leshow** [comment]
Thank you for such a quick response, however it's quite late here, I have replace the relevant line and will give feedback on login tomorrow

**Comment by belak** [comment]
Sounds good. I'd like to get feedback from the person who originally removed the input redirection as well, since I don't completely understand why it was removed yet... so I'm not in a huge rush.

**Comment by leshow** [comment]
This may not be the right place to ask this either but, when I enable 'gpg' in conjuction with 'ssh', I get a 'gpg-agent is already running' on every term open. Any ideas about that?

**Comment by belak** [comment]
Unfortunately, I don't... I'm not very familiar with the gpg package.

**Comment by flying-sheep** [comment]
sorry: i think #1480 fixed it the correct way. the [man](http://man.openbsd.org/ssh-add.1) [page](https://linux.die.net/man/1/ssh-add) states:

> If ssh-add needs a passphrase, it will read the passphrase from the current terminal if it was run from a terminal. **If ssh-add does not have a terminal associated with it but DISPLAY and SSH_ASKPASS are set**, it will execute the program specified by SSH_ASKPASS (by default “ssh-askpass”) and open an X11 window to read the passphrase. This is particularly useful when calling ssh-add from a .xsession or related script. **(Note that on some machines it may be necessary to redirect the input from /dev/null to make this work.)**

so the only way that’s guaranteed to work everywhere is

- require the user to set SSH_ASKPASS and DISPLAY
- use redirect `</dev/null`

**Comment by belak** [comment]
Thanks for clarifying @flying-sheep. I think you're right... and after testing in an Ubuntu VM, the current code seems to work as expected. If I open a tty first, I'm prompted for the password and my ssh identity is added... if I open a terminal first, the same thing happens... and it's shared properly between both the terminal and the tty.

I don't think the issue @leshow is running into is what I originally thought.

One thing that's good for testing this: you can run `ssh-add -l` to list keys and `ssh-add -D` to clear all keys.

**Comment by leshow** [comment]
@flying-sheep I would assume there are plenty of of people that use zsh on their servers, myself included. Under those scenarios I never enter an xsession. What would my value for DISPLAY and SSH_ASKPASS be under those circumstances? Because this is essentially the problem I'm running into.

**Comment by belak** [comment]
@leshow DISPLAY would be blank and it wouldn't trigger the code which uses ssh askpass... it should ask in the terminal for your password using the askpass built-in to ssh-add.

**Comment by leshow** [comment]
I have already tried the `init.zsh` in https://github.com/sorin-ionescu/prezto/pull/1480/files and It did not ask me for a password after logging in to tty.

**Comment by leshow** [comment]
FYI, https://github.com/sorin-ionescu/prezto/pull/1490/files this didn't work for me

**Comment by belak** [comment]
I think I see the problem. If there are no identities defined, it essentially runs `ssh-add ""` which doesn't load any identities.

**Comment by belak** [comment]
I've pushed a fix in 109864429cea5763e57c77f060835bfcdbefb09f. This was tested in X in an Archlinux VM, but I'm fairly sure this will solve the problem elsewhere. The problem was that the ssh identities were being expanded to an empty string, which meant ssh-add thought it wasn't supposed to load any. Removing the quotes should fix the expansion.

Thanks for your patience! If you're still seeing this issue, let me know and I'll re-open this for more investigation.

**Comment by flying-sheep** [comment]
very nice! is it possible that there’s a space in one of the identities (which would probably break the quoteless version)?

> I would assume there are plenty of of people that use zsh on their servers, myself included. Under those scenarios I never enter an xsession. What would my value for DISPLAY and SSH_ASKPASS be under those circumstances? Because this is essentially the problem I'm running into.

as @belak said: it would be empty and it wouldn’t work. that’s because `ssh-add`’s two modes (terminal and SSH_ASKPASS) are both for manual input. SSH_ASKPASS is for manual *graphical* input. using SSH_ASKPASS for automation is just a thing people do, not the purpose of `ssh-add`.

so you have to say “yeah, sure, i’m in a graphical environment (DISPLAY) and will now type my password using the graphical prompt (SSH_ASKPASS)”. but then you use a CLI application that fills in your password automatically instead.

and that’s why you have to set both DISPLAY and SSH_ASKPASS.

**Comment by belak** [comment]
I did some initial testing with a space and it seemed to work, even with the quoteless version. I believe it's because we're doing filename expansion which doesn't need the quotes.

**Comment by flying-sheep** [comment]
cool! maybe we should add a comment explaining that as well, before someone touches this piece of highly sensitive code.

**Comment by leshow** [comment]
> so you have to say “yeah, sure, i’m in a graphical environment (DISPLAY) and will now type my password using the graphical prompt (SSH_ASKPASS)”. but then you use a CLI application that fills in your password automatically instead.

But what if you have neither DISPLAY, nor have access to a graphical prompt? In that case, will it now just run successive ssh-add's on all the keys lsted in the module?

**Comment by flying-sheep** [comment]
> But what if you have neither DISPLAY, nor have access to a graphical prompt?

hmm, i’m not sure we’re on the same page here. please read carefully. what i’m talking about is that `ssh-add` is *designed* to either

- read the password from the terminal, or
- read it from a graphical prompt (the binary of which is specified by `SSH_ASKPASS`)

so according to the documentation, if you don’t have `DISPLAY` or access to a graphical prompt, you have to type your password into the terminal manually.

> [But I want to (ab)use `SSH_ASKPASS` to provide my password automatically]

OK, so you want to trick `ssh-add` into thinking it’s in a graphical environment, so that it will use `SSH_ASKPASS`. to do that, you can

- either set `DISPLAY='dont-mind-me'` temporarily just to trick `ssh-add`, and unset `DISPLAY` after loading the prezto ssh module
- or patch and recompile ssh-add to not check for it

**Comment by leshow** [comment]
Thank you for the explanation @flying-sheep 

@belak https://github.com/sorin-ionescu/prezto/commit/109864429cea5763e57c77f060835bfcdbefb09f

This works great for me, same behaviour as before (asks my ssh pass on login)

**Comment by flying-sheep** [comment]
ideally, you’d set it directly before calling ssh-add and unset it after. however, as prezto loads the ssh module, which in turn calls ssh-add, this this is AFAIK not possible from the suer side.

we could maybe add a `zstyle` module option to the ssh module, which sets DISPLAY for you to trick `ssh-add`…

but if 109864429cea5763e57c77f060835bfcdbefb09f fixes your use case already, then we don’t have to bother.

**Comment by belak** [comment]
It could be done manually with some hackery... I believe by calling zmodload ssh either at the bottom of zpreztorc or at the end of the zshrc.

**Comment by flying-sheep** [comment]
i see, so just loading it separately from the other modules. OK, fine, that solves it then.
