### ISSUE TITLE
Ctrl-C causes sorin prompt to display x130

### ISSUE THREAD

**Issue by wonbyte** [sorin-ionescu/prezto#1522]
### Description

if you hit Ctrl-c the soring theme will display x 130. Hitting return does not clear the x 130. You have to run another command
### Expected behavior

If Ctrl-c is supposed to display x 130 (i'm not sure), when you hit return the x 130 should disappear
### Actual behavior

x130 does not disappear from prompt until you run another command
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Versions

  - Prezto commit: 82d3265ad510f366a0
  - ZSH version: zsh 5.4.2 (x86_64-apple-darwin17.0.0)
  - OS information: macOS High Sierra 10.13.2
<img width="485" alt="screen shot 2017-12-28 at 8 19 38 pm" src="https://user-images.githubusercontent.com/681965/34427878-773caeca-ec0c-11e7-93ef-1bc033163d73.png">

**Comment by belak** [comment]
This seems to be an upstream zsh behavior.

```
# This runs zsh with no rc files, so prezto is not loaded
% zsh -f
# This is the return code (the 130 you're seeing in the sorin prompt and a separator)
Kalebs-MBP% PROMPT='%?%#'
0% # I hit ^C here
130% # I hit enter here. You can see the 130 doesn't go away.
130%ls # I ran a command here which returned 0.
Applications	Desktop		Downloads	Library		Music		Public		i3
Code		Documents	Dropbox		Movies		Pictures	cc_inventory
0%
```

If you don't want to see the return code and just want to see the red x, you can disable the return code display as explained here: https://github.com/sorin-ionescu/prezto/tree/master/modules/prompt#display-return-value

I'd be happy to answer any other questions, but as this seems to be an intentional upstream behavior, I'm going to close this. Thanks for mentioning it!
