### ISSUE TITLE
Directory color is too dark on Mac (allow users to define LS_COLORS)

### ISSUE THREAD

**Issue by danilcha** [sorin-ionescu/prezto#1539]
Prezto is [hardwired](https://github.com/sorin-ionescu/prezto/blob/master/modules/utility/init.zsh#L93) to use dark blue for directory color both for `ls` and for completion on Mac, which is barely visible on black terminal. 

I can override `LSCOLORS` (for `ls`) by executing this after I load Prezto:
```
export LSCOLORS="ExGxBxDxCxEgEdxbxgxcxd" # ls colors like in Linux
```
It makes directory color light blue, and in general I like Linux colors better, e.g. green executables.

Unfortunately, I cannot do the same for `LS_COLORS` (for completion): redefining them before or after I load Prezto has no effect, probably because they are already copied to `zstyle ':completion:*' list-colors`.

You probably will not change your default colors to Linux, but maybe you could use the existing value of `LS_COLORS` if it was defined and not override it?

Update:

Found a way to override them:
```
export LSCOLORS='ExGxBxDxCxEgEdxbxgxcxd' # ls colors like in Linux
# used https://geoff.greer.fm/lscolors/ to convert them to LS_COLORS:
export LS_COLORS='di=1;34:ln=1;36:so=1;31:pi=1;33:ex=1;32:bd=1;34;46:cd=1;34;43:su=0;41:sg=0;46:tw=0;42:ow=0;43' 
zstyle ':completion:*:default' list-colors "$LS_COLORS"
```

**Comment by sunoterra** [comment]
@danilcha 

one may also specify custom `ls` color settings in the [~/.zlogin](/sorin-ionescu/prezto/blob/master/runcoms/zlogin) file. [this file](/sorin-ionescu/prezto/tree/master/runcoms#zlogin) is sourced after all others (besides ~/.zlogout of course)

i like to use [solarized colors](https://github.com/seebi/dircolors-solarized). so, in my ~/.zlogin, i add a line after my pathing housework settings (e.g. see [zprofile](/sorin-ionescu/prezto/blob/master/runcoms/zprofile) settings, which i put in ~/.zlogin), similar to one of the following:
```
eval "$(dircolors ~/.dircolors)" # coreutils
eval "$(gdircolors ~/.dircolors)" # macos with gnu coreutils
```
where ~/.dircolors contains a choice of color spec

sourcing these environment settings for non-login/interactive shells can be done from [~/.zshenv](/sorin-ionescu/prezto/blob/master/runcoms/zshenv). choosing this route means one has to remember to update the example loading provided to look for and load ~/.zlogin instead of ~/.zprofile

**Comment by sunoterra** [comment]
@belak that [#1546 PR](/sorin-ionescu/prezto/pull/1546) is an excellent start, for sures. i updated my setup to use the standard ~/.dir_colors named file instead of the ~/.dircolors file i was using.

this is my current colors config:
```
if [ ls --color -d . >/dev/null 2>&1 ]
then
  eval "$(gdircolors ${HOME}/.dir_colors)"
  zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
else
  LSCOLORS="gxfxbEaEBxxEhEhBaDaCaD"
  export LSCOLORS
  zstyle ':completion:*:default' list-colors ${(s.:.)LSCOLORS}
fi

```
do you think that compensation will have to be made for gnu coreutils built on macos via homebrew and/or macports? i.e. using `gdircolors` instead of `dircolors`.

**Comment by belak** [comment]
We traditionally haven't included support for gnu coreutils on osx, but it would be nice to see changes which add it.

**Comment by vinamelody** [comment]
Hi, I agree with @danilcha and recently started using this on catalina. 
What is the updated way to do this on the latest version? Thanks in advanced

**Comment by belak** [comment]
If you set `LSCOLORS` (or `LS_COLORS` depending on the platform) before loading prezto in your zshrc, the settings should be respected.

**Comment by vinamelody** [comment]
thanks @belak for the tips ... i decided to go with replacing iTerm's blue color instead :)

**Comment by geonnave** [comment]
Adjusting the `Minimum Contrast` within `Preferences ... -> Profiles -> Colors` to the value `60` can also be a solution for this -- see https://stackoverflow.com/a/37822585.
