### ISSUE TITLE
Underwhelming visual effect with Fire and Fade prompts

### ISSUE THREAD

**Issue by carlca** [sorin-ionescu/prezto#1558]
### Description
Blocky appearance of certain prompts eg fire and fade

### Expected behavior
I expected a smooth visual fade effect, possibly with the aid of tweaked fonts a la Powerline

Ditto

### Actual behavior
Blocky visual effect. I don't know if this is expected or not. 
From my system...

![screen shot 2018-03-09 at 12 01 30](https://user-images.githubusercontent.com/260612/37207530-5e750160-2395-11e8-85e6-7c7a36a57cab.png)

The screenshots at http://mikebuss.com/2014/04/07/customizing-prezto/ make me think that I am expecting too much here!

### Steps to Reproduce

1. Install zsh
2. Install prezto
3. prompt fire 

### Versions

  - Prezto commit:
 b3c27bb
  - ZSH version:
5.3.1
  - OS information:
macOS 10.13.3 High Sierra

**Comment by belak** [comment]
I just checked and it looks like the fire prompt is included with zsh itself and not as a part of prezto. We don't aim to override these prompts to add prezto features because, as you've noticed, some of them are (as you put it) a bit underwhelming. I'd recommend checking out some of the prompts we bundle with prezto:

```
agnoster
cloud
damoekri
giddie
kylewest
minimal
nicoulaj
paradox
peepcode
powerlevel9k
powerline
pure
skwp
smiley
sorin
steeef
```

There are a few additional themes in the [prezto-contrib](https://github.com/belak/prezto-contrib) repo (including the one I'm using) if you don't find one in the main prezto that you like. My personal favorites from the main prezto repo are agnoster and sorin.

Thanks for filing the issue - I'm always happy to clear stuff like this up. If you have any questions about the supported prompts, definitely feel free to comment or file another issue here.

**Comment by carlca** [comment]
Thanks for the reply Belak, your explanation makes perfect sense. I've settled on `steeef` for the time being as being a cool mixture of uncomplicated but attractive form combined with a decent amount of useful functionality!

**Comment by carlca** [comment]
Update: I've found the Chauncey Garrett theme and now my terminal looks like this...

I think it looks quite neat embedded in VSCode's terminal window!

![screen shot 2018-03-09 at 21 01 34](https://user-images.githubusercontent.com/260612/37229798-209675ac-23dd-11e8-9ab3-cf87f07550b6.png)
