### ISSUE TITLE
Sorin theme not working in JetBrains Intellij

### ISSUE THREAD

**Issue by tchlyah** [sorin-ionescu/prezto#1575]
### Description

Sorin theme not doesn't show well in Intellij Idea terminal. 

I tried [ryanoasis/nerd-fonts](https://github.com/ryanoasis/nerd-fonts) but it doesn't work as well.

### Versions

  - Prezto commit: b6b43eb331a893d9a278c278b20534a2ca07aed0
  - ZSH version: 5.3
  - OS information: macOS High Sierra, Windows 10
  - Intellij Idea version: 2017.3

**Comment by belak** [comment]
Could you post a screenshot of what you're seeing? I think this is most likely an issue with the terminal included with Intellij, but I'd like to investigate before deciding for sure.

**Comment by tchlyah** [comment]
![image](https://user-images.githubusercontent.com/3661112/38983313-52caac12-43c4-11e8-9a03-b4967bb3064e.png)

**Comment by duydo** [comment]
I had same issue with PyCharm, Intellij 
<img width="1395" alt="screen shot 2018-05-07 at 1 59 59 pm" src="https://user-images.githubusercontent.com/197841/39688914-0b9ae778-51ff-11e8-8de0-0b494572a1c9.png">

**Comment by tchlyah** [comment]
Any news about that?

**Comment by singularitti** [comment]
@belak Same here. The theme adds 3 blank lines after each "return".

**Comment by belak** [comment]
It looks like this is a combination of a number of things, based on the screenshot above. The JetBrains terminals don’t appear to handle many Unicode characters correctly.

The prompt should be a single line but it appears to be a few characters over when in these terminals. This means a `\r` which zsh and prezto can use to redisplay the prompt will cause a new line to appear because `\r` only goes to the start of the current line in your terminal.

It looks like this is because this terminal is treating any unknown Unicode characters as double-width when they’re really not... Specifically the arrows next to the directory name. Because ZSH sees them as single-width but the terminal is incorrectly displaying them as double width, the terminal displays past the end of the line which makes every prompt redisplay cause a new line.

You may be able to work around this by using some of the tricks mentioned [here](https://superuser.com/questions/655607/removing-the-useless-space-at-the-end-of-the-right-prompt-of-zsh-rprompt) (even though those tricks are for hiding an extra space at the end of the line, you should be able to use the same settings to increase the padding rather than decrease it).

I don’t think this is a bug in prezto... there’s no good way to work around a terminal which doesn’t display things properly, though if you manage to find a way I would be open to suggestions or pull requests. 

Optionally you could switch to a prompt which doesn’t use Unicode characters. I specifically designed my prompt (It’s called “belak” and located in the contrib repo) to display info similar to prezto and not use Unicode characters because I kept running into issues like this.

**Comment by indrajitr** [comment]
This used to happen in IntelliJ IDEA 2018.1 but has been resolved in IntelliJ IDEA 2018.2 (which is in EAP now). We can close possible close this.

**Comment by tchlyah** [comment]
I confirm that it was corrected in Intellij IDEA 2018.2.
