### ISSUE TITLE
Modules 'Pacman': drop alias 'pacu'

### ISSUE THREAD

**Issue by frozenxuan** [sorin-ionescu/prezto#1576]
Arch Linux had deprecated ABS (source: https://www.archlinux.org/news/deprecation-of-abs/)
The alias 'pacu' should be dropped and probably merge with 'pacU'.

**Comment by belak** [comment]
Thanks for filing this. It looks like this was already fixed with https://github.com/sorin-ionescu/prezto/commit/14670f40f0191a8dc219b98eae48d9e8113f16c9

If you're still seeing usage of abs, there's a chance you're using the old community fork which was deprecated, but you should have seen a warning that the community was deprecated on startup.
