### ISSUE TITLE
Paradox adds an extra blank line before the prompt

### ISSUE THREAD

**Issue by uda** [sorin-ionescu/prezto#1666]
### Description
I am using the paradox prompt, it is the best I have used so far. One thing really bothers me though, the theme has an additional blank line, which makes the terminal really padded, previous commands disappear too quickly.

https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/functions/prompt_paradox_setup#L148-L151

### Expected behavior
Two line prompt

### Actual behavior
Three line prompt - an extra blank line

### Steps to Reproduce

1. Set paradox as the prompt theme
2. Open a new terminal
3. A blank line will appear before each prompt

### Versions

  - Prezto commit: a338cba805f63f770e9078925bc5c46129e28bde
  - ZSH version: 5.4.2
  - OS information: Linux Mint 19.1 Cinnamon

### P.S.

I already fixed this on one of my PCs, and I am not sure a fix is required for all, since many use it and nobody complained so far, but might if this change is introduced.
So maybe the proper solution is to create a paradox theme spin-off.

**Comment by johnpneumann** [comment]
Thanks for the report. Indeed I think that changing this would probably end up upsetting more folks than not as this behavior has been in place since the prompt was added (a7a49129). I think that doing as you suggested and creating a forked version of it would be the best option. You can place the prompt in any location within your `$fpath` and it will be available for loading ([see here](https://github.com/sorin-ionescu/prezto/tree/master/modules/prompt#theming)).
