### ISSUE TITLE
.zprezto/modules/prompt/functions/prompt_powerlevel10k_setup containing theme powerlevel10k

### ISSUE THREAD

**Issue by moltar** [sorin-ionescu/prezto#1720]
### Description

Getting the following error on a new term window after `zprezto-update`:

```
Couldn't read file ~/.zprezto/modules/prompt/functions/prompt_powerlevel10k_setup containing theme powerlevel10k.
```

### Expected behavior

No errors.

### Actual behavior

Errors.

### Steps to Reproduce

1. Run `zprezto-update`
2. Open a new term instance / window.

### Versions

  - Prezto commit: `e94b6b2078ccd0b289293dc4b996983a96a34681`
  - ZSH version: `zsh 5.3 (x86_64-apple-darwin18.0)`
  - OS information: macOS latest

**Comment by giorni** [comment]
Powerlevel10K may be not installed.

`git submodule update --init` at yours prezto path to install and update all submodules to latest prezto version.

**Comment by moltar** [comment]
That indeed does fix the problem.

Any reason why `prezto-update` doesn't do that automatically?

Thanks.

**Comment by belak** [comment]
When prezto-update was initially created (https://github.com/sorin-ionescu/prezto/pull/1344), we decided on `git submodule update --recursive` because we don't often add new subrepos. powerlevel10k is an exception to our general rule - there needs to be a very good reason to add a new subrepo so new deps is something we didn't think of. I'm not sure if --init should be added or not.

**Comment by belak** [comment]
CC @samcv 

Do you have any opinions on this? Would it be worth adding `--init` to the zprezto-update function?
