### ISSUE TITLE
async_job:zpty:12: no such pty command: prompt_sorin

### ISSUE THREAD

**Issue by kronikpillow** [sorin-ionescu/prezto#1754]
there is a similar issue but it is from 2017 at #1509 and seems the error is back ..

### Description
I installed it following instructions on the readme in the prezto repo

### Expected behavior

I expect everything to work fine

### Actual behavior

after every start of my terminal i get a 
async_job:zpty:12: no such pty command: prompt_sorin

### Versions

  - Prezto commit: current
  - ZSH version: 5.7.1-1
  - OS information: Artix Linux

**Comment by belak** [comment]
Dupe of #1736

**Comment by ceres-c** [comment]
Also note that some people were reporting this with the sorin prompt as well. If you're seeing it there, please file a new issue so we can track that separately. Thanks!

_Originally posted by @belak in https://github.com/sorin-ionescu/prezto/issues/1736#issuecomment-584780727_

Given this message, I'd like to know if you could open this issue again in order to get fixed the prompt_sorin error as well
