### ISSUE TITLE
init.zsh:123 yields parse error near `zle`

### ISSUE THREAD

**Issue by sinkr** [sorin-ionescu/prezto#1801]
### Description
init.zsh, line 123 prior to and including git commit c7fe32f2639f4643be0fff034dd58dacc9b29e10 issues an error "parse error near `zle`".

### Expected behavior
No error is displayed upon a new zsh shell.

### Actual behavior
This error is displayed upon a new zsh shell session:
`$HOME/.zprezto/modules/editor/init.zsh:123: parse error near `zle'`

### Steps to Reproduce

1. Install zprezto per instructions in the Github page
2. start a new zprezto session by invoking zsh

### Versions

  - Prezto commit: c7fe32f2639f4643be0fff034dd58dacc9b29e10
  - ZSH version: zsh 5.8 (x86_64-apple-darwin19.3.0)
  - OS information: macOS 10.15.3

**Comment by sinkr** [comment]
Thank you for any insight into this--this has been going on across many zprezto releases, however, I finally decided to dig into it.

**Comment by belak** [comment]
Hi! It looks like you're using a fork of prezto (https://github.com/chauncey-garrett/zsh-prezto) and not actually this repo, so you'd be better off switching to this repo or filing this issue there.

In any sense, it looks like a missing `fi` on line 109 of `modules/editor/init.zsh` in that fork.

Additionally, because it's not actually related to this repo, I'm going to close this for now.

**Comment by sinkr** [comment]
Hi Kaleb,

Sorry for the confusion, and thank you so much for the response!
