### ISSUE TITLE
Setting up Python modules causes zsh to crash.

### ISSUE THREAD

**Issue by huideyeren** [sorin-ionescu/prezto#1977]
### Description

When I try to load a Python module with zpreztorc's `zstyle ':prezto:load' pmodule` setting, zsh starts and crashes immediately.

Note that I'm using "powerlevel10k" as the theme.

### Expected behavior

To be able to use Python modules in prezto.

### Actual behavior

1. When using zsh as login shell and setting Python modules to load and starting iterm2, iterm2 terminates after a few seconds.
2. When I start zsh from bash, I get the zsh prompt, but then I get the bash prompt
3. I checked the log from the console of my Mac and found no logs that looked like that.
4. I tried reinstalling gdbm from Homebrew, but that didn't make any difference at all.
5. I tried switching the configuration with zpreztorc and found that zsh started when I disabled loading Python modules.

### Steps to Reproduce

1. Install Prezto.
2. Open zpreztorc and configure it to load powerlevel10k and the Python module.
3. Make sure that zsh crashes.

### Versions

  - Prezto commit: 7884fb2271d131bb492fafc4eba1c537a821092b
  - powerlevel10k version: v1.16.0
  - ZSH version: 5.8 (x86_64-apple-darwin21.0)
  - OS information: macOS Monterey version 12.2

**Comment by zbirenbaum** [comment]
I was having the same issue, but to be honest I would not use the python plugin. The documentation is excessively poor, the code is a nightmare for anyone who doesn't live in zsh scripts, and it definitely hasn't been updated any time recently or maintained otherwise this could not possibly be an issue.

As to your issue, I would bet my life you use virtualenvwrapper, or have it somewhere on your system. The logic requires the virtualenv-init plugin to be present in order to properly load the virtualenvwrapper plugin. The virtualenvwrapper plugin does not rely on virtualenv-init though, so this is ridiculous, and then the code begins an 'else' statement which will inevitably discover the script in your pyenv plugins dir and attempt to source it.

This will always cause a crash. Try running it in a terminal to test it out. Additionally, if you set the 'initialize' option to false for virtualenvwrapper, the script will not attempt to source it and your crashes will stop.

Honestly this plugin is such a bugfest because it tries to account for what everyone might need from it. Just write your own config for loading virtualenv stuff.

**Comment by huideyeren** [comment]
@zbirenbaum 

Thank you for the information.

I do indeed have virtualenvwrapper installed. However, I don't think I'm using virtualenvwrapper consciously these days, since I'm mostly using pipenv and poetry.

Probably the best way is to not use Python plugins. Currently I have stopped running the Python plugin, but I don't feel any inconvenience for now.

**Comment by zbirenbaum** [comment]
> @zbirenbaum 
> 
> 
> 
> Thank you for the information.
> 
> 
> 
> I do indeed have virtualenvwrapper installed. However, I don't think I'm using virtualenvwrapper consciously these days, since I'm mostly using pipenv and poetry.
> 
> 
> 
> Probably the best way is to not use Python plugins. Currently I have stopped running the Python plugin, but I don't feel any inconvenience for now.

You can always just configure stuff in your zprofile and rc. Since I submitted a PR which addresses both your problem and mine please keep this open so it doesn't appear the issue is solved when it isn't.
