### ISSUE TITLE
question about dir_color eval

### ISSUE THREAD

**Issue by LuanVSO** [sorin-ionescu/prezto#1993]
https://github.com/sorin-ionescu/prezto/blob/7ec1ecde3a2b5f195432259bb32934cfd16dd5bc/modules/utility/init.zsh#L91
whats the `(.N)` supposed to do in this line?
in my system it is preventing .dir_colors from being matched

**Comment by indrajitr** [comment]
`(.N)` is composition of two separate [Glob Qualifiers](https://zsh.sourceforge.io/Doc/Release/Expansion.html#Glob-Qualifiers).
- `.` checks if `$HOME/.dir_colors` is a plain file.
- `N` sets the `NULL_GLOB` option for `$HOME/.dir_colors` (In ZSH parlance, when `NULL_GLOB` is set, if a pattern for filename generation has no matches, delete the pattern from the argument list instead of reporting an error).

These two qualifiers together effectively means, if `$HOME/.dir_colors` doesn't exist as a plain text file, the line `eval "$(dircolors --sh $HOME/.dir_colors(.N))"` reduces to `eval "$(dircolors --sh)"` instead of `eval "$(dircolors --sh $HOME/.dir_colors)"`.

Hope this helps troubleshooting further.

**Comment by LuanVSO** [comment]
Thanks, my .dir_colors was a symlink to .dircolors
