### ISSUE TITLE
Symbols show as odd chars in prompt

### ISSUE THREAD

**Issue by kyounger** [sorin-ionescu/prezto#217]
I'm sure this isn't an OMZ-exclusive issue, but perhaps it can be solved at that level. I'm using the sorin theme, but cannot get any of the symbols to show up at the command line prompt when SSHing into my mac from a windows machine running putty. I have tried every single combination of settings in putty, including making sure UTF was set (per the only suggestion from google I could find).

Is this futile?

**Comment by zxwind** [comment]
Just ran into similar issue. Turns out set letter space properly will fix the prompt display in Inconsolata.

**Comment by Offirmo** [comment]
Tried a lot of fonts (from https://github.com/powerline/fonts) **Dejavu Sans Mono** works, as told by @kyounger Out of the 5 other I tried, only Dejavu Sans Mono works.

**Comment by jgabarca** [comment]
I dug through the link posted by @kyounger. Here's a recap of what worked for me:
I added a new value to
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontLink\SystemLink`
as indicated on https://msdn.microsoft.com/en-us/goglobal/bb688134.aspx to link backup fonts to supply characters missing from a base font. I linked DejaVu Sans Mono to Source Code Pro. After a relogin on windows the issue was fixed.
