### ISSUE TITLE
syntax-highlighting does not appear to work

### ISSUE THREAD

**Issue by skwp** [sorin-ionescu/prezto#302]
As per instructions, added
`zstyle ':prezto:module:syntax-highlighting' color 'yes'`

to ~/.zpreztorc. Tried as well in ~/.zprofile

The highlighting does not appear to be active...I need a little guidance as to where to look for this. I put an echo before the line and it is getting executed. I also tried to execute on command line and it seems to do nothing.

**Comment by mayuroks** [comment]
This happened to me as well since I followed the instructions on this page
[prezto syntax-highlighting](https://github.com/sorin-ionescu/prezto/tree/master/modules/syntax-highlighting)

zsh / prezto beginners would easily miss out on loading the modules part
```zsh
zstyle ':prezto:load' pmodule \
  'syntax-highlighting' \
```

I think this cabe quickly added to the [prezto syntax-highlighting](https://github.com/sorin-ionescu/prezto/tree/master/modules/syntax-highlighting) page.
