### ISSUE TITLE
failed to create symbolic Error

### ISSUE THREAD

**Issue by ansdma** [sorin-ionescu/prezto#323]
Hi, I'm trying to Create a new Zsh configuration by copying the Zsh configuration files provided. However I get this error?

```
ln: failed to create symbolic link `/home/ans/.zlogin': File exists
ln: failed to create symbolic link `/home/ans/.zlogout': File exists
ln: failed to create symbolic link `/home/ans/.zpreztorc': File exists
ln: failed to create symbolic link `/home/ans/.zprofile': File exists
ln: failed to create symbolic link `/home/ans/.zshenv': File exists
ln: failed to create symbolic link `/home/ans/.zshrc': File exists
```

**Comment by alimoeeny** [comment]
@Alghamdi  it is not stupid at all, the readme does not explain what you should do with it, and it should.

**Comment by sorin-ionescu** [comment]
Replace `ln` with `ln -f` to overwrite existing files.

**Comment by Alghamdi** [comment]
@alimoeeny thanks for bringing this back to life ;). 
@sorin-ionescu thanks for this great piece of code, since 2012 I've been using it for every single machine I have access to, and since then I now know how to get it to work, how to branch it, how to commit my changes and how to update it :). Perhaps adding such guid for newbies would save lots some hassles.

**Comment by alimavrakis** [comment]
:+1: Thanks

**Comment by karltaylor** [comment]
Just reiterating what @alimoeeny said, I was confused where to create a new `zsh` config as referred to in Step 3 of installation.

**Comment by belak** [comment]
We'd be open to PRs with clarification and improvement... Or even more concrete suggestions. It's sometimes hard to see what the best way to make it more accessible is when you're so used to how it works, so a fresh set of eyes might be best.
