### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by shyamsalimkumar** [sorin-ionescu/prezto#568]
This is not so much an issue, rather a question. How would I uninstall Prezto? How should I proceed? Is it just `rm -rf ${ZDOTDIR:-$HOME}/.zprezto` and then `chsh -s /bin/sh`?

**Comment by ODelibalta** [comment]
Thanks for the topic. just tried installing it because of all the hype about how faster this is compared to oh my zsh ... at least oh my zsh has better instructions on the install. "Hey add these lines to your zsh config" oh okay "now open a new terminal window" oh okay "failed to create symbolic link zshrc already exists" sweet it already failed ... I am out
