### ISSUE TITLE
README.md typos?: prompt_name_preexec vs. prompt_name_precmd

### ISSUE THREAD

**Issue by wem3** [sorin-ionescu/prezto#609]
In ~/.zprezto/modules/{editor git node python ruby}/README.md

Please accept my apologies if this shouldn't be submitted as an issue (I'm still more than a little green), but I've been ferociously confused by instructions to add hooks to the `prompt_name_preexec` function, as all of the examples that I looked at call `prompt_name_precmd` in a file likewise named 'prompt_name_precmd'.

Is this a typo? I could see it being the case that prompt_name_preexec is a kind of function, and people have consistently chosen to define it as prompt_name_precmd.

**Comment by MPNussbaum** [comment]
@wem3 Did you ever find where the prompt_name_preexec function was?

**Comment by sorin-ionescu** [comment]
`s/name/name_of_theme/g`

**Comment by MPNussbaum** [comment]
I don't understand what you're saying. Would you please explain?

I can't find the hook function prompt_name_preexec in order to call python_info, as seen here in the final step:

![screen shot 2015-06-04 at 4 10 12 pm](https://cloud.githubusercontent.com/assets/2239453/7993492/70eb579a-0ad4-11e5-88d7-5f7055dd080f.png)

Any help would be appreciated.

**Comment by sorin-ionescu** [comment]
Replace **name** with the name of the theme, for example prompt\_**sorin**\_preexec.

**Comment by MPNussbaum** [comment]
That's not where I'm confused. There is no function named prompt_sorin_preexec in the prompt_sorin_setup file.

As @wem3 mentioned, there is a prompt_name_precmd.

**Comment by sorin-ionescu** [comment]
You just define it. It's called by the prompt system.
