### ISSUE TITLE
Environment variables are not set in xterm

### ISSUE THREAD

**Issue by DarthGandalf** [sorin-ionescu/prezto#614]
When zsh is run in xterm, SHLVL is 2. This causes .zprofile not to be sourced, and environment is not set properly.
There are other cases when SHLVL is not 1.

Let's revert 3a5fff9c6d8e62032f0173476aed73afcd00578e ?

If one needs to skip overwriting environment in subshell, they can use `zsh -f`

**Comment by ff2000** [comment]
I just ran into this issue:
https://github.com/neovim/neovim/issues/4417
Executing commands from within neovim didn't pick up executables from within ~/bin because $PATH didn't contain ~/bin because .zprofile wasn't sourced because SHLVL was >1.
I am running startx directly from TTY, so I am logged in a szh before X starts. No login manager involved. I also run nvim (and vim, which also suffers from this problem) from within zsh (urxvt->tmux->zsh).
