### ISSUE TITLE
Use the POSIX function syntax

### ISSUE THREAD

**Issue by sorin-ionescu** [sorin-ionescu/prezto#692]
Presently, Prezto uses `function foo {}`, which is a KornShell (`ksh`) compatibility syntax. Switch to the POSIX `foo () {}` syntax.

See http://wiki.bash-hackers.org/scripting/obsolete for more obsolete syntax supported by both BASH and Zsh.

**Comment by Eriner** [comment]
Patch for fix here: 

https://github.com/Eriner/prezto/commit/4dfba0c4b06c64dd08cddd8c7b2c6daed5991112.patch

**Comment by sorin-ionescu** [comment]
Thank you.

**Comment by belak** [comment]
The PR was closed, but @Eriner left this useful snippet, which should make most of the needed changes:

`find . -path *external* -prune -o -type f -print0 | xargs -0 sed -r -i 's/(function )(.*)\s\{/\2\(\) \{/g'`

**Comment by belak** [comment]
Is there any reason (aside from POSIX compliance) we don't want to keep `function` at the start? It seems easier to grep for and it's much clearer what's being defined. My honest opinion would be to go in the opposite direction and add `function` to everything... but I'm fine as long as we're consistent.

**Comment by Eriner** [comment]
`function` declares the function to operate as a ksh-compatible function.

**Comment by belak** [comment]
Thanks for following up. Unfortunately I can't find any information to back up those claims. The man pages seem to imply that either is fine to use:

```Shell functions are defined with the function reserved word or the special syntax `funcname ()'.```

Also:

```
function word ... [ () ] [ term ] { list }
word ... () [ term ] { list }
word ... () [ term ] command
```

I can't find any information in the man pages (for current versions - maybe it was something in an old version) about how they're treated differently (though I may be missing something - it's easy to miss stuff in the zsh man pages) and both sections on function declaration in zshmisc don't mention anything about ksh or a difference between declaration types.

Bash also does the same thing: all function declaration types are treated the same.

**Comment by Eriner** [comment]
> If they do behave the same and it's not considered deprecated, is there any reason to avoid it?

Again, sorry for not having any documentation on hand, but I believe there is in fact a difference in the way it's handled by the shell, something about the function scope or alias interaction, but I don't remember. I'm sure I have a comment on GitHub somewhere about it, so I'll try to dig it up.

But the reason to avoid it is because it's non-POSIX, and because it's a legacy feature support from a shell no one uses anymore, and because of that it's non-standard. I

> It seems easier to grep for

While true, IMO that's a non-usecase. You're either going to debug the environment, search for the name of a function you're looking for, or just `which`. I can't think of a single case where `grep 'function '` is something that anyone would use.

**Comment by belak** [comment]
I should have clarified earlier that I just see it as easier to read (as well as easier to grep for) but it may just be me because I'm more used to other languages.

> `function` declares the function to operate as a ksh-compatible function. Zsh treats these functions slightly differently, though I don't have any references for that on hand.

http://zsh.sourceforge.net/FAQ/zshfaq02.html

```Functions defined with `function funcname { body }' behave the same way as those defined with `funcname () { body }'. In ksh, the former behave as if the body were read from a file with `.', and only the latter behave as true functions.```

https://unix.stackexchange.com/a/73854

The [bash hackers](http://wiki.bash-hackers.org/scripting/obsolete) link mentioned in the first page seems to say that bash treats all functions the same... and I'd assume zsh went for bash compatibility rather than ksh. It also mentions that there are differences in ksh, but as we're not targeting ksh, that shouldn't matter.

> But the reason to avoid it is because it's non-POSIX, and because it's a legacy feature support from a shell no one uses anymore, and because of that it's non-standard.

My personal opinion is that non-POSIX syntax isn't a great reason to avoid a feature in a zsh-only project. There's no way prezto would support zsh and other shells. It would be way too complicated. We're way past requiring POSIX compliant syntax because of the additional things we can get from zsh (extended glob, variable expansion, etc). It may have come from another shell but I can't find *any* information in the official documentation claiming it should be avoided or that it's a legacy/non-standard feature.

Complete POSIX compliance is a good thing when you're targeting other shells because it lets you focus on a common subset, but if you are (just as an example) a zsh configuration framework, you don't need to worry as much about sticking to that subset.

Here's the bash docs on functions:

https://tiswww.case.edu/php/chet/bash/bashref.html#Shell-Functions

```This defines a shell function named name. The reserved word function is optional. If the function reserved word is supplied, the parentheses are optional. The body of the function is the compound command compound-command (see Compound Commands). That command is usually a list enclosed between { and }, but may be any compound command listed above, with one exception: If the function reserved word is used, but the parentheses are not supplied, the braces are required. compound-command is executed whenever name is specified as the name of a command. When the shell is in POSIX mode (see Bash POSIX Mode), name may not be the same as one of the special builtins (see Special Builtins). Any redirections (see Redirections) associated with the shell function are performed when the function is executed.```

These are the only things listed under the POSIX Mode portion:

```
12. Function names must be valid shell names. That is, they may not contain characters other than letters, digits, and underscores, and may not start with a digit. Declaring a function with an invalid name causes a fatal syntax error in non-interactive shells.
13. Function names may not be the same as one of the POSIX special builtins.
14. POSIX special builtins are found before shell functions during command lookup.
15. When printing shell function definitions (e.g., by type), Bash does not print the function keyword.
...
32. Assignment statements preceding POSIX special builtins persist in the shell environment after the builtin completes.
33. Assignment statements preceding shell function calls persist in the shell environment after the function returns, as if a POSIX special builtin command had been executed.
...
44. When the set builtin is invoked without options, it does not display shell function names and definitions.
```

None of those seem to mention any differences with how functions are executed.

It may be valid to call it non-standard among shells, but it's supported by the zsh documentation that it's not deprecated.

It's even mentioned in the porting from csh faq that using the function keyword can be useful because the function name itself won't be expanded by aliases.

Sorry for the wall of text, just wanted to make sure all the info I could find is available to everyone without having to dig through man pages for 45 minutes.

**Comment by Eriner** [comment]
Ah, yes!

> It's even mentioned in the porting from csh faq that using the function keyword can be useful because the function name itself won't be expanded by aliases.

As I mentioned before, I remembered it had something to do with scope, and this is the one. 

> My personal opinion is that non-POSIX syntax isn't a great reason to avoid a feature in a zsh-only project. 

We're not making the change to make the project "POSIX compliant" or anything, simply bringing the function definitions in line with standard shell function definitions. the `funcname() { ... }` syntax has been the standard shell function definition syntax for a long time, and the `function funcname() { ... }` style was only added as a ksh-ism, and wasn't meant to replace the POSIX syntax. 

> I should have clarified earlier that I just see it as easier to read (as well as easier to grep for) but it may just be me because I'm more used to other languages.

FWIW, every other shell-based project I've worked on has defined functions the standard POSIX way, to the point that when I first saw it in prezto it was slightly jarring.

**Comment by belak** [comment]
zsh itself uses a mix of the two styles.

https://github.com/zsh-users/zsh/blob/ed4e37e45c2f5761981cdc6027a5d6abc753176a/Functions/Prompts/prompt_zefram_setup

https://github.com/zsh-users/zsh/blob/ed4e37e45c2f5761981cdc6027a5d6abc753176a/Functions/Prompts/prompt_bart_setup

Just as an example in a single folder.

The oh-my-zsh style guide *wishes* it could prefer the keyword style:

`The `function` keyword is optional when `()` is present after the function name, but it aids readability and prevents [conflicts with alias declarations](http://zsh.sourceforge.net/Doc/Release/Shell-Grammar.html#Aliasing).`

But they fall back to POSIX because it's a standard.

My argument is the other direction. Why would we give up readability for the sake of a standard which hasn't been updated in almost 10 years (2008 appears to be the latest release)?

**Comment by Eriner** [comment]
> Why would we give up readability for the sake of a standard

It's not for the sake of the standard, it's *for the sake of what everyone is used to seeing and working* with. It might be worth noting that if you do the opposite of this issue/PR, there may be cases where it breaks functions that are effectively used as complex aliases, though I'm not sure what the specific interactions with `autoload` are here, if any.

Not that oh-my-zsh is a good standard to base much opinion on, but there's a reason that they use the POSIX syntax: everyone else does, specifically bash. Anyone who eventually works on zsh typically starts working in bash, and almost every bash scripting resource defines functions using the POSIX syntax. Wooledge resources are a good example.

And from Sorin's link above:

> This is an amalgamation between the Korn and POSIX style function definitions - using both the function keyword and parentheses. It has no useful purpose and no historical basis or reason to exist. It is not specified by POSIX. It is accepted by Bash, mksh, zsh, and perhaps some other Korn shells, where it is treated as identical to the POSIX-style function. It is not accepted by AT&T ksh. It should never be used. See the next table for the function keyword. Bash doesn't have this feature documented as expressly deprecated.

**Comment by belak** [comment]
> I wouldn't use prompt setup scripts as a "code correctness" reference, even if they're in the zsh repo.

It's not just prompts. They do the same thing in completion scripts and also random autoloaded functions provided with zsh.

> _for the sake of what everyone is used to seeing and working_ with

This is a large generalization. While it's mostly true, even Google's style guide allows for using the function keyword if it's consistent across a project. Most of the zsh functions even have something like `# function zfanon {` at the top. They don't use `# zfanon () {`. There *are* places where it is used.

And the final paragraph which is quoted may be true, but there absolutely no indication in either set of documentation (bash or zsh) which says that the function keyword is not recommended.

However, I quoted the [Google Shell Style Guide](https://google.github.io/styleguide/shell.xml) which I think solves a larger issue with the project (no recommended style). We already do a decent job of following it, but not everything is perfect... and while they mention the keyword syntax, it seems to be as a secondary option.

After weighing the options, even though I disagree with it, my recommendation is to drop the function keyword. However, I'd like to propose a second unrelated recommendation that `# x () {` should be included with all autoloaded functions (along with the closing brace) to make them easier to grep for and so you can grep for builtin and autoloaded functions at the same time.

**Comment by belak** [comment]
I've clarified some of the style rules in e52523204b69f18746a2d22f433c831919973bfa but the existing functions still need to be updated (and we need to decide if we want to do anything about autoloaded functions).

**Comment by belak** [comment]
Ok, I've changed my mind on this again after talking with a number of people. Literally all the functions in the project use the `function x {}` syntax and it's clearer, easier to search for, and isn't documented as deprecated (aside from on some random wiki pages). The mashup syntax of `function x () {}` won't be allowed.
