### ISSUE TITLE
Problem in modules/node?

### ISSUE THREAD

**Issue by pikeas** [sorin-ionescu/prezto#765]
At line #18:

    # Return if requirements are not found.
    if (( ! $+commands[node] )); then
      return 1
    fi

If `nvm alias default XYZ` has been run, node is added to PATH:

    ~ echo $+commands[node]                                                                                                                                                         
    0
    ~ source $(brew --prefix nvm)/nvm.sh
    ~ echo $+commands[node]
    1

Prezto's script sources NVM identically but exits early, instead of adding completions.

**Comment by qur2** [comment]
Hi,

I ran in the exact same problem and pinned down the problem to the same line.
`nvm` is working fine. However, there is no node executable until the user runs `nvm use 0.10`. Only then, node is added to the path.
The problem in prezto/modules/node/init.zsh is that it runs when the shell is opened. Obviously, at that time, the user didn't run `nvm use 0.10` yet, which make the prezto `node-info` function to be unloaded (because `if (( ! $+commands[node] ))` fails).

At the moment, I just comment the check and it runs fine. I suppose it's because `nvm` is there and running `nvm current` without any node activated just return an empty string.

So removing the check `if (( ! $+commands[node] ))` would be my fix. I can send in a PR if that all makes sense.

**Comment by ohcibi** [comment]
+1 for that... the `if (( ! $+commands[node] ))` breaks my prompt unless there is 

1. a node version installed
2. if installed with nvm it must be either used or an alias for default must be set

Its not only that it does not generate completions but it also does not source the `node-info` and `node-doc` functions. I understand that those functions are useless if there is no node installed but if one includes the `node` module, those functions should exist no matter what. The functions could even throw errors like "don't include me: no node installed", or the module could throw that by itself when starting the shell, as long as something clearly reports that there is a `node` command missing.

**Comment by pikeas** [comment]
@sorin-ionescu Why did you close this before merging @qur2's pull request? Did you make any other changes not linked here?
