### ISSUE TITLE
modules/directory vs modules/utility

### ISSUE THREAD

**Issue by leoj3n** [sorin-ionescu/prezto#851]
I feel there is some organizational inconsistency between the [`directory` module](https://github.com/sorin-ionescu/prezto/blob/c98da90662a11e7ac1e046ccd6a99edd21e68312/modules/directory/init.zsh) and the [`utility` module](https://github.com/sorin-ionescu/prezto/blob/c98da90662a11e7ac1e046ccd6a99edd21e68312/modules/utility/init.zsh) because they both include aliases related to directory switching. My opinion is the directory aliases should all be in the directory module or all in the utility module and not split up between two modules. Thoughts on this?

**Comment by sorin-ionescu** [comment]
You might be right. They remained in utility after the project was forked from Oh-My-Zsh. Utility ought to contain stuff that doesn't fit anywhere else.

**Comment by ressu** [comment]
Both of the directory and utility modules also need a way to disable some of the safeties. Both of the modules contain useful things but for someone who lives in the terminal shell, all the safeties get in the way.

I was just about to send a pull request adding a safety-off option to the utility module which would have disabled the interactivity in cp, mv & friends. But after thinking about it a bit, I realized that utility should be split into parts as well. The dircolors part should be in a separate module. It's not really an utility, but rather a feature that manipulates ls and friends. Same goes for the other coloring options.

As for the directory module, things like unsetting CLOBBER do not fit in to directory behaviour.

**Comment by sorin-ionescu** [comment]
@ressu, submit your changes, and I'll have a look. If you make constant backups, safety is not useful; if you don't, it very much is. I have been burned many times by overwriting or deleting the wrong file; it ceased when I have turned on safety.

**Comment by ressu** [comment]
I'll see if I manage to get back to the changes this weekend. I undid all my changes after I started thinking about the organization a bit.

As for the safety settings, I've found that too much safety makes you careless since you can always rely on the safety net to catch you if you make a mistake. What happens when you don't have the safety net in place?

In any case, my solution was to add a flag that allows the user to disable the interactivity in certain commands, but leave it undocumented. Even if I prefer to not use safeties, I don't want to promote disabling them.

**Comment by leoj3n** [comment]
@belak Should revisit this perhaps?
