### ISSUE TITLE
Usage suggestion?

### ISSUE THREAD

**Issue by N4M3Z** [sorin-ionescu/prezto#860]
Dear Sorin, dear authors,

thank you very much for creating such a clean and consistent `zsh` framework. I am a former user of `oh-my-zsh` and have recently switched to `zgen` in order to manage plugins manually. Mostly because I have a different philosophical view on how plugins and functions should be handled.  

I noticed that `prezto` is unmatched in its structure, consistency, documentation and the usage of `zstyle` while offering a sensible amount of modules, and also externally linked submodules (e.g. syntax-highlighting from zsh-users). 

Now, my problem is that even though I agree with most of `prezto` structure and code logic, I still like to do some small local changes here and there. Some of these are implemented in `prezto` through `zstyle`, some require deeper changes. So far, I simply copy pasted modules and in the process started creating my own framework. At this point, I wonder whether it would be more productive to have my own fork of `prezto`, since that would allow me to contribute as well as properly credit the original authors.

Now, in order to consider a fork, I would like to pose a few very general questions:
1) Are the developers still active? What is the road map for the future?
2) How rigid are your code standards? Would you consider discussing possible changes (e.g. changing module `init.zsh` to `<module>.plugin.zsh` to improve compatibility with `antigen` or `zgen`?
3) Would you consider integrating more modules? For example, StackExchange/blackbox that would provides easy handling for encrypted files and thus allows users to store history files in versioning systems. Are there any guidelines as to what modules are accepted and which are not?
4) Considering folder structure of `prezto`, I prefer to separate themes and machine specific `profiles` in different folders, is that something you would consider? Integrating `blackbox` would also introduce another folder `keyrings`.

I might have more questions down the line, I am currently deciding on the best course of action regarding the management of `zsh` plugins on my systems. Thank you for your time and keep up the good work.

**Comment by sorin-ionescu** [comment]
Prezto is designed to be forked, modified in place, and managed via Git.

1. The developer is still active.
2. The code standards are rigid to prevent the Wild, Wild, West of Oh-My-Zsh. I will not rename `init.zsh` since your suggestion makes no sense in the Prezto context. Prezto has no core. All of it is modular. Use what you need; ignore the rest. Not all modules are independent. Some modules depend on others.
3. Pull requests are welcome. If a module is useful to many, not just you, and it's written to the Prezto standards, it will be merged.
4. Native Zsh themes, which Prezto uses, unlike Oh-My-Zsh, are auto-loadable function files placed anywhere in `$FPATH`. In Prezto, they are stored in `modules/prompt/functions`. For machine specific profiles, you could add a `zshrc.local` file and have Prezto load it, or you can add a `profiles` module with a file or directory named after each machine and have Prezto load the appropriate one at runtime. You can have as many files and folders as you want in a module directory. Prezto only cares about `init.zsh` and the `functions` directory.

Smart questions are always welcome.

**Comment by N4M3Z** [comment]
Dear Sorin,

thank you for answering. I have started experimenting with `prezto` on my own terms. I created a `profiles` module as you suggested and it seems to be working fine (will send a pull request when its up to the standards). Nearly all questions have been answered by the project's documentation, so I only have a few (and probably not smart):

1. What is the reason you are consistently avoiding the shebang?
2. Do you have a guideline on what functions should go into separate `functions` directory and which to keep inside init.zsh? It seems impractical to have a multitude of files for one-line functions.
3. What is your standard for code comments? Would you consider Markdown or perhaps even Doxygen? There is an initiative to have a limited support for shell: https://github.com/Anvil/bash-doxygen.

Concerning point 2. in the previous discussion, I probably did not express myself clearly. I understand that `prezto` is entirely modular, that is why it felt natural to have it compatible with other "load" systems like `zgen`. In any case, we have already implemented `zgen` so that the module is loaded if it contains an `init.zsh`. I completely agree that there is something to having a consistent module structure, especially after I figured it might be worth to have aliases and key bindings in a separate file for every module. I just made it so that `prezto` would load these automatically as well:
```
      # Load module aliases
      if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/modules/$pmodule/alias.zsh" ]]; then
        source "${ZDOTDIR:-$HOME}/.zprezto/modules/$pmodule/alias.zsh"
      fi

      # Load module key bindings
      if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/modules/$pmodule/bindkey.zsh" ]]; then
        source "${ZDOTDIR:-$HOME}/.zprezto/modules/$pmodule/bindkey.zsh"
      fi
```
Would you be interested in a pull request for this? I am still not sure whether it is better to have just `init.zsh` or `$pmodule.init.zsh` as it seems mighty easier to search and discern files named like `$pmodule.init.zsh` or `$pmodule.alias.zsh`. Please let me know what you think if you have the time, I am sure you have been thinking about this when coming up with the concept of `prezto`.

**Comment by sorin-ionescu** [comment]
There is no need for shebang since nothing in Prezto is an executable script.

Big functions and rarely used functions should go into the functions directory; it keeps load time small.

There is no need for complicated code comments; doxygen does not support Zsh. Use grammatically correct American English.

Most modules are small, the exception is Git; so, such abstractions are not necessary. I prefer to load `init.zsh` and let `init.zsh` load the rest as needed. I don't want a giant, overly complicated `pmodload` function; it's big as it is.

There is no need to repeat the module name in module files. Use a fuzzy file finder.
