### ISSUE TITLE
Git completion not recognizing aliases

### ISSUE THREAD

**Issue by elmart** [sorin-ionescu/prezto#861]
Hi, and thanks for zprezto. I'm really glad using it.

A small annoyance I've found is that git completion doesn't seem to recognize aliases. For example, I have `co` aliased to `checkout`, but typing `git co  <tab>` doesn't list branch names, as it should, but instead, I get current dir's files.

This works fine with bash completion. That's why I suppose it's something related to git completion included here.

Thanks.

**Comment by sorin-ionescu** [comment]
The Git completion is shipped with Zsh, not Prezto, and Prezto does not modify it. Unless it reads the gitconfig file, it has no way of completing them. I don't remember if it does since I have not used Git aliases in years. Prezto comes with many Git aliases. Read the Git module README. See `gco`, for example.

**Comment by elmart** [comment]
Ok, closing then.
