### ISSUE TITLE
url-quote-magic needs bracketed-paste-magic in zsh 5.1

### ISSUE THREAD

**Issue by lucy** [sorin-ionescu/prezto#978]
https://github.com/zsh-users/zsh/blob/a9df6aaa702abf761b155cd842a7f6917be44139/Functions/Zle/url-quote-magic#L11

**Comment by Eriner** [comment]
@lucy, thanks for that. I had a local-workaround for myself but I was unaware of the *actual* solution. I have a proposed change in my fork of prezto where I've been fixing things, seeing as Sorrin seems to be letting this die. https://github.com/Eriner/prezto/commit/d7f1559682e285497cd93de6b745872f6e616e59

**Comment by 2vek** [comment]
@sorin-ionescu pasting urls have become annoyance right now with zsh 5.1,  you have to either escape or qoute them.
```
~$  mpv https://www.youtube.com/watch?v=HcgJRQWxKnw
zsh: no matches found: https://www.youtube.com/watch?v=HcgJRQWxKnw
~$  
```

These changes to `modules/environment/init.zsh` brings old behaviour back (Thanks @lucy) -
```patch
-autoload -Uz url-quote-magic
+autoload -Uz url-quote-magic bracketed-paste-magic
 zle -N self-insert url-quote-magic
+zle -N bracketed-paste bracketed-paste-magic
```

**Comment by nick-s-b** [comment]
After I upgraded to zsh 5.2, I immediately noticed the paste/escape issue. After applying changes above to init.zsh as suggested by @2vek, pasting works but the screen output looks messed up. Display/highlight of the cursor position is deceptive too.

5.0.7:
![5 07](https://cloud.githubusercontent.com/assets/7957590/12005180/28c998ba-ab64-11e5-8d53-96dfaaeae1b4.jpg)

5.2.0:
![5 2](https://cloud.githubusercontent.com/assets/7957590/12005184/47ddcfd2-ab64-11e5-936f-2e23529c78ca.jpg)

Anyway, hope this can be somehow fixed. I went back to 5.0.7 because I haven't noticed any errors with it yet.

**Comment by sorin-ionescu** [comment]
@nick-s-b Does it happen if you turn off syntax-highlighting?

**Comment by DarthGandalf** [comment]
yes, it happens even without syntax-highlighting

**Comment by DarthGandalf** [comment]
Btw, screen gets messed up on bracketed paste even in `zsh -f`, without prezto. Pressing any key unmesses it, and highlights syntax again if syntax-highlighting is used.
So I assume that this was supposed to actually be a feature: to show what was pasted. I don't like this feature though...

**Comment by 2vek** [comment]
any reason to keep this issue around for so long? I have been using this patch since I posted here, without any problem.

Highlighting problem @nick-s-b mentions is minor compared to usability benefit this feature has. As @DarthGandalf  said it can be solved by pressing any key. When I paste something, usually I press `spacebar` or other keys to extend/edit the command or just `enter` to execute it. This should not be blocking issue IMHO.

**Comment by kajka** [comment]
Hi, there! I started today switching from oh-my-zsh to prezto but I encountered the problem descibed in posts above. The trick mentioned by @2vek & @lucy does not seem to work.

Used version of ZSH: 5.4.2.
Does anyone know any way to work around this problem?
