### ISSUE TITLE
shortcut for reverse-i-search 

### ISSUE THREAD

**Issue by tuxayo** [sorin-ionescu/prezto#989]
I just updated Prezto and now Ctrl-R doesn't trigger "reverse-i-search".
Did the shortcut changed or could this be a bug?

Prezto r1557.32f3b57
zsh 5.1.1
Arch Linux with kernel 4.2.2

**Comment by sorin-ionescu** [comment]
Unless you use vi, it should be bound.

```sh
bindkey -L | grep '\^R'
bindkey "^R" history-incremental-pattern-search-backward
```

**Comment by lorrin** [comment]
I'm in vi mode, but I'd still like to bind Ctrl-R to reverse search.

If I start up a session and manually issue `bindkey "^R" history-incremental-pattern-search-backward`, it works just fine afterwards. But if I put the same bindkey in my `~/.zpreztorc`, it has no effect. Why not?

**Comment by sorin-ionescu** [comment]
It should have an effect if you put it at the end of the file.

**Comment by lorrin** [comment]
OK, I figured it out. Putting it at the end of `.zpreztorc` does not work because `init.zsh` loads `.zpreztorc` first, and then afterwards it initializes the modules, including (by default) `editor`, which in turn does a `bindkey -d` to restore the default bindings. That undoes whatever bindings were in `.zpreztorc`. If I put my bindkeys at the end of `.zshrc` instead, they run after prezto startup is done and it works.

But, having read through the bindings in `editor`, I'm going to leave Ctrl-R at the prezto default of `redo` and use `?` and `/` to do my history searches from `vicmd` mode.

**Comment by sorin-ionescu** [comment]
Put it at the end of **zshrc**.

**Comment by tuxayo** [comment]
> Unless you use vi, it should be bound.

I was indeed in vi bindings, thanks!

Are the vi bindings the defaults?

**Comment by sorin-ionescu** [comment]
Emacs is default.
